[package]
name = "vuget"
version = "0.1.0"
description = "Desktop Personal Widget"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
sysinfo = "0.36"
winreg = "0.55"
dirs = "6"
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
panic = "abort"
